addpath('helper_functions', 'capnet', 'sticker_classifier', 'plyToPos')

% TODO: make configurable?
% Parameters for the run
%toolPath = 'E:\MATLAB\cap_classifier\VisualSFM_windows_64bit\VisualSFM';
toolPath = '"C:\Program Files\VisualSFM_windows_64bit\VisualSFM"'; %Path of VisualSFM executable file
%sourceFiles = dir('E:\globus_data\**\*.avi'); %replace with location of raw vid files
sourceFiles = dir('C:\Globus\emberson-consortium\VideoRecon\RESULTS\**\*.MP4'); %replace with location of raw vid files
%sourceFiles = dir('C:\Globus\emberson-consortium\VideoRecon\MATLAB\model\*.MP4'); %replace with location of raw vid files
%mniModelPath = "C:\Globus\emberson-consortium\VideoRecon\MATLAB\infantModelMNI.mat"; % Used by plyToPOS.m
mniModelPath = "C:\Globus\emberson-consortium\VideoRecon\MATLAB\FixModelMNI.mat"; % Used by plyToPOS.m
%TODO: replace nirsModelPath with the file generated by plyToPOS?
nirsModelPath = "C:\TEMP\NIRS_adult.mat"; % Used by plyToPos.m
%nirsModelPath = "C:\Globus\emberson-consortium\VideoRecon\MATLAB\model\NIRS_model.mat"; % Used by plyToPos.m
frameSkip = 4; % How much frames to skip (process 1 frame in each frameSkip + 1 frames
useVideo = true; % Whether to use a video file directly or already extracted frame images
shimadzuFileName = "infant"; % Name of shimadzu output file in the video directory
stickerGroupSize = 5; % for modelStars, 20 is used (for capStars it's fine to have outliers)
radiusToStickerRatio = 8;% Relative distance for which 2 points are considered the same sticker
outputDirPrefix = "adult";
spmPath = "C:\Users\Dean\Documents\MATLAB\spm12"; % spm installation path
spmFNIRSPath = "C:\Users\Dean\Documents\MATLAB\spm_fnirs"; % spm_fnirs installation path

% Inner use consts
connectionsFileName = "connections.txt";
vsfmInputDirName = "vsfmInput";
vsfmOutputFileName = "dense"; % Name of nvm file outputed by VSFM
imgResultFilePrefix = "img_result";

%%%%%%%%% Start %%%%%%%%%
data = load(fullfile('capnet', filesep, 'model.mat'));  %TODO: allow loading model from separate path?
net = data.net;

% TODO: Make this part optional?
% Take only the relevant infants
infantNumbers=1:1:1; %this array defines which infants should we process
vidSubFolders = 'E:\globus_data\infant'; %hopefully videos are in subdirectories called "infant x"
infantToSearch = [repmat(vidSubFolders, length(infantNumbers), 1), string(infantNumbers)'];
infantToSearch = strcat(infantToSearch(:,1),infantToSearch(:,2));
[Lia,Locb] = ismember(infantToSearch,{sourceFiles.folder});
index = 1;
%file_indices = Locb';
fileIndices = 1:length(sourceFiles);

for i = fileIndices
    fprintf("Processing file number %d\n", i);
    
    % TODO: use video folder name for output folder?
    % Create output directory if needed
    outputDir = sprintf('%s%sresults%s%s%d_results_stride_%d', ...
        pwd, filesep, filesep, outputDirPrefix, infantNumbers(index), frameSkip+1);
    if ~exist(outputDir, 'dir')
        mkdir(outputDir);
    end
    
    vsfmInputDir = fullfile(outputDir, vsfmInputDirName);
    frameRate = createInputImages(useVideo, sourceFiles(i), net, imgResultFilePrefix, ...
        vsfmInputDir, frameSkip);    
    makeListAndConnection(vsfmInputDir, round(frameRate), frameSkip, imgResultFilePrefix, ...
        connectionsFileName);
    runVSFM(outputDir, vsfmInputDir, connectionsFileName, toolPath, vsfmOutputFileName);
     
    % Video folder should also contain a stickerHSV.txt file (information on sticker locations)
    % and an infant.txt file (the Shimadzu output file)
    vidDir = sourceFiles(i).folder;
    %stickerHSVPath = strcat(vidDir, filesep, "stickerHSV.txt");
    stickerHSVPath = "C:\TEMP\stickerHSV.txt";
    load(stickerHSVPath, 'stickerHSV');
    %shimadzuFilePath = strcat(vidDir, filesep, shimadzuFileName, ".txt");
    shimadzuFilePath = "C:\TEMP\adult.txt";
    %plyFilePath = strcat(outputDir, filesep, vsfmOutputFileName, ".0.ply");
    plyFilePath = "C:\TEMP\denseNet.0.ply";
    fprintf("Converting .ply file to .pos file\n");
    plyToPosOutputDir = strcat(outputDir, filesep, "plyToPosOutput");
    addpath(spmPath, genpath(spmFNIRSPath));
    plyToPOS(plyFilePath, stickerHSV, mniModelPath, shimadzuFilePath, plyToPosOutputDir, ...
        nirsModelPath, stickerGroupSize, radiusToStickerRatio);
    
    index = index+1;
end

function runVSFM(outputFolder, inputFolder, connectionsFileName, toolPath, vsfmOutputFileName)
    args = strcat(" sfm+pairs+sfm+pmvs ", inputFolder, filesep, "list.txt ", ...
        outputFolder, filesep, vsfmOutputFileName, ".nvm ", inputFolder, filesep, ...
        connectionsFileName);
    vsfmCmd = strcat(toolPath, args);
    fprintf("Running VisualSMF with the following command:\n%s\n", vsfmCmd);
    system(vsfmCmd);
end
